[package]
name = "yclient"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
anyhow = "1"
yew = "0.17.4"
wasm-bindgen = "0.2.67"
failure = "0.1"
serde = "1"
serde_derive = "1"
url = "2.1"
base64 = "0.13"

[lib]
crate-type = ["cdylib", "rlib"]
